trigger:
- main

stages:

- stage: CI
  displayName: "CI"
  jobs:

  - job: Security
    displayName: "Gitleaks Scan"
    pool:
      name: 'Vikas-Pool'

    steps:
    - checkout: self

    - script: |
        gitleaks detect --source . --exit-code 1
      displayName: "Run Gitleaks"


  - job: Lint
    displayName: "Code Lint"
    dependsOn: Security
    pool:
      name: 'Vikas-Pool'

    steps:
    - checkout: self

    - script: |
        chmod +x mvnw
        ./mvnw spring-javaformat:validate
      displayName: "Run Lint"


  - job: Build
    displayName: "Maven Build and SonarQube"
    dependsOn: Lint
    pool:
      name: 'Vikas-Pool'

    steps:
    - checkout: self

    - task: SonarQubePrepare@7
      displayName: "Prepare SonarQube"
      inputs:
        SonarQube: 'Pet-Clinic-SVC'
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectKey=spring-petclinic-devops-e2e
          sonar.projectName=Spring PetClinic DevOps E2E
          sonar.branch.name=
          sonar.scanner.skipJreProvisioning=true

    - script: |
        chmod +x mvnw
        ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.7.0.6970:sonar -Dsonar.branch.name=
      displayName: "Maven Build, Test and SonarQube"

    - task: SonarQubePublish@7
      displayName: "Publish SonarQube Results"
      inputs:
        pollingTimeoutSec: '300'



- stage: Docker
  displayName: "Build and Push Docker Image"
  dependsOn: CI

  jobs:

  - job: Docker
    displayName: "Build and Push to ACR"
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - checkout: self

    - task: AzureCLI@2
      displayName: "Build and Push Image to ACR"
      inputs:
        azureSubscription: 'Pet-Clinic-Azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |

          echo "Azure CLI"
          az version

          echo "Docker Version"
          docker version

          echo "Login to ACR"
          az acr login --name petclinicvikasacr

          echo " Build Docker Image "
          docker build \
            -t petclinicvikasacr.azurecr.io/spring-petclinic:$(Build.BuildId) \
            .

          echo "Tag Latest"
          docker tag \
            petclinicvikasacr.azurecr.io/spring-petclinic:$(Build.BuildId) \
            petclinicvikasacr.azurecr.io/spring-petclinic:latest

          echo "Push Build ID Image"
          docker push \
            petclinicvikasacr.azurecr.io/spring-petclinic:$(Build.BuildId)

          echo "Push Latest Image"
          docker push \
            petclinicvikasacr.azurecr.io/spring-petclinic:latest

          echo "Docker Images"
          docker images | grep spring-petclinic

- stage: Deploy_DEV
  displayName: "Deploy to DEV - Container Apps"
  dependsOn: Docker

  jobs:

  - job: DeployDev
    displayName: "Deploy Spring PetClinic to DEV"
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: AzureCLI@2
      displayName: "Deploy to Azure Container Apps"
      inputs:
        azureSubscription: 'Pet-Clinic-Azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |

          echo "Azure CLI"
          az version

          echo "Deploying image:"
          echo "petclinicvikasacr.azurecr.io/spring-petclinic:$(Build.BuildId)"

          az containerapp update \
            --name petclinic-dev \
            --resource-group petclinic-rg \
            --image petclinicvikasacr.azurecr.io/spring-petclinic:$(Build.BuildId)

          echo "Deployment completed"

          echo "Container App Status"
          az containerapp show \
            --name petclinic-dev \
            --resource-group petclinic-rg \
            --query "{status:properties.runningStatus,image:properties.template.containers[0].image,url:properties.configuration.ingress.fqdn}" \
            -o table